"""Schemas for AI-generated research reports.

The central safety property of this module: **no field the AI produces is
numeric.** `ResearchNarrative` is entirely prose and lists of prose. The model is
therefore structurally incapable of emitting a value that the application would
store, chart, or present as a measurement. Every number the UI displays comes
from `schemas/stock.py` or `schemas/indicators.py`, which are populated only by
the market-data provider and the indicator calculations.

`ResearchNarrative` is passed to the Anthropic API as a JSON Schema via
structured outputs, so the response shape is enforced at the API boundary, and
is then validated a second time by Pydantic on receipt. A report that fails
either check is discarded rather than partially rendered.
"""

from __future__ import annotations

from datetime import date, datetime

from pydantic import BaseModel, ConfigDict, Field, field_validator

from app.core.exceptions import InvalidTickerError
from app.core.validation import normalize_ticker
from app.schemas.stock import utcnow

# Fixed, non-negotiable legal text. The model is asked to supply a `disclaimer`
# so its output matches the documented contract exactly, but whatever it returns
# is replaced with this constant before the report leaves the service. Legal
# wording must never vary between generations.
STANDARD_DISCLAIMER = (
    "This report is generated by an AI system from publicly available market "
    "data and is provided for informational and educational purposes only. It "
    "is not financial advice and is not a recommendation to buy, sell, or hold "
    "any security. The analysis may be incomplete, out of date, or incorrect, "
    "and market data may be delayed. Always conduct your own research and "
    "consult a qualified financial professional before making any investment "
    "decision."
)


class ResearchRequest(BaseModel):
    """Request body for `POST /api/research`."""

    ticker: str = Field(
        ...,
        description="Ticker symbol to research. Normalized to uppercase.",
        examples=["AAPL"],
    )
    refresh: bool = Field(
        default=False,
        description="Bypass the cached report and generate a new one.",
    )

    @field_validator("ticker")
    @classmethod
    def _validate_ticker(cls, value: str) -> str:
        """Re-raise as ValueError so FastAPI renders a 422, not a 500."""
        try:
            return normalize_ticker(value)
        except InvalidTickerError as exc:
            raise ValueError(exc.message) from exc


class ResearchNarrative(BaseModel):
    """The exact structure the language model must return.

    Used directly as the JSON Schema sent to the Anthropic API. Constraints:

    * `extra="forbid"` produces `additionalProperties: false`, which structured
      outputs requires and which stops the model inventing extra keys.
    * `bull_case` and `bear_case` each require at least two entries. This is how
      the balance requirement is enforced mechanically rather than by asking
      politely in the prompt: a report that argues only one side fails
      validation and is rejected.
    * Every field is a string or a list of strings. There is deliberately no
      numeric field anywhere in this model.
    """

    model_config = ConfigDict(extra="forbid")

    company_summary: str = Field(
        min_length=1,
        description="What the company does and how it makes money.",
    )
    recent_performance: str = Field(
        min_length=1,
        description="Interpretation of the supplied price action and news.",
    )
    technical_analysis: str = Field(
        min_length=1,
        description="Interpretation of the supplied technical indicators.",
    )
    fundamental_analysis: str = Field(
        min_length=1,
        description="Interpretation of the supplied fundamental metrics.",
    )
    bull_case: list[str] = Field(
        min_length=2,
        description="Distinct arguments supporting a positive view.",
    )
    bear_case: list[str] = Field(
        min_length=2,
        description="Distinct arguments supporting a negative view.",
    )
    risks: list[str] = Field(
        min_length=1,
        description="Specific downside risks.",
    )
    catalysts: list[str] = Field(
        min_length=1,
        description="Identifiable events that could move the stock either way.",
    )
    neutral_conclusion: str = Field(
        min_length=1,
        description=(
            "Even-handed summary. States the tension between the cases without "
            "issuing a verdict, recommendation, or price target."
        ),
    )
    disclaimer: str = Field(
        min_length=1,
        description="Replaced server-side with the canonical disclaimer.",
    )


class DataSourceRef(BaseModel):
    """Attribution for one dataset used to build a report."""

    dataset: str = Field(description="Which dataset, e.g. 'quote' or 'indicators'.")
    provider: str = Field(description="Provider that supplied it.")
    retrieved_at: datetime = Field(description="When it was fetched, UTC.")


class ResearchReport(BaseModel):
    """A completed research report, as returned by the API.

    Carries the narrative plus the provenance the UI needs to show where the
    underlying data came from and how fresh it is.
    """

    symbol: str
    generated_at: datetime = Field(default_factory=utcnow)
    model: str = Field(description="AI model that produced the narrative.")
    cached: bool = Field(
        default=False,
        description="True if served from cache rather than newly generated.",
    )

    # -- Provenance --------------------------------------------------------
    price_as_of: date | None = Field(
        default=None, description="Date of the latest close used in the analysis."
    )
    data_sources: list[DataSourceRef] = Field(default_factory=list)

    # -- Narrative ---------------------------------------------------------
    company_summary: str
    recent_performance: str
    technical_analysis: str
    fundamental_analysis: str
    bull_case: list[str]
    bear_case: list[str]
    risks: list[str]
    catalysts: list[str]
    neutral_conclusion: str
    disclaimer: str
